const labelMessagePairs = [
  ["Broken hearted", "Happened for a reason"],
  ["Broken hearted", "Don’t lose hope."],
  ["Broken hearted", "Healing takes time; be gentle with yourself."],
  ["Broken hearted", "This pain is temporary"],
  ["Broken hearted", "Let go of what was"],
  ["Broken hearted", "Your heart will heal and love again."],
  ["Broken hearted", "Every end is a new beginning."],
  [
    "Broken hearted",
    "It’s okay to feel sad; it’s part of the healing process.",
  ],
  ["Broken hearted", "You are stronger than you think."],
  ["Broken hearted", "Better days are ahead."],
  ["Broken hearted", "Embrace the lessons this experience brings."],
  ["Broken hearted", "Allow yourself to grieve and then to grow."],
  ["Broken hearted", "Pain is a sign that you cared deeply."],
  ["Broken hearted", "Every wound will eventually heal."],
  ["Broken hearted", "Time will lessen the pain and bring new joys."],
  ["Broken hearted", "Your heart has the capacity to heal and love again."],
  ["Broken hearted", "The right love will find you when you are ready."],
  ["Broken hearted", "This too shall pass."],
  ["Broken hearted", "You are not alone; reach out to loved ones."],
  ["Broken hearted", "Each day brings new strength and new hope."],
  ["Lost person", "You will find your way."],
  ["Lost person", "This season is part of your journey."],
  ["Lost person", "Trust the process; you are on the right path."],
  ["Lost person", "Clarity will come with time."],
  ["Lost person", "Every step"],
  ["Lost person", "It’s okay to not have all the answers right now."],
  ["Lost person", "Trust in your inner compass."],
  ["Lost person", "You are exactly where you need to be right now."],
  ["Lost person", "Your path will reveal itself in due time."],
  ["Lost person", "Embrace the uncertainty; it’s part of the adventure."],
  ["Lost person", "Sometimes being lost leads to the best discoveries."],
  ["Lost person", "Take it one day at a time."],
  ["Lost person", "Keep moving forward; your direction will become clear."],
  ["Lost person", "Your journey is unique and valuable."],
  ["Lost person", "Every experience is shaping you for your future."],
  ["Lost person", "You are not alone in feeling lost; many have been there."],
  ["Lost person", "Trust that you will find your way."],
  ["Lost person", "Listen to your heart; it knows the way."],
  ["Lost person", "You have the strength to navigate this uncertainty."],
  ["Lost person", "This feeling is temporary; you will find clarity soon."],
  ["Scared person", "Don’t let fear hold you back."],
  [
    "Scared person",
    "Fear is just an indication that you’re close to something great.",
  ],
  ["Scared person", "Courage is feeling the fear and doing it anyway."],
  ["Scared person", "You are braver than you believe."],
  ["Scared person", "Face your fears"],
  ["Scared person", "Fear is temporary"],
  ["Scared person", "Embrace the unknown; it’s where growth happens."],
  ["Scared person", "Your fears are smaller than they seem."],
  [
    "Scared person",
    "Take one step at a time; you don’t have to see the whole staircase.",
  ],
  ["Scared person", "Fear is a natural part of the journey."],
  ["Scared person", "You have the strength to overcome your fears."],
  ["Scared person", "The only way out is through."],
  ["Scared person", "Your courage will inspire others."],
  ["Scared person", "Fear is just a feeling; it doesn’t control you."],
  ["Scared person", "Step out of your comfort zone; that’s where life begins."],
  ["Scared person", "You are stronger than your fears."],
  ["Scared person", "Trust yourself; you have what it takes."],
  ["Scared person", "Every great achievement begins with the decision to try."],
  ["Scared person", "You are capable of more than you know."],
  ["Scared person", "Fear is a sign that you are on the right track."],
  ["Person ready to give up", "Don’t give up"],
  ["Person ready to give up", "Keep going; your breakthrough is near."],
  ["Person ready to give up", "Persistence is the key to success."],
  ["Person ready to give up", "You’ve come too far to quit now."],
  ["Person ready to give up", "The darkest hour is just before dawn."],
  ["Person ready to give up", "Your efforts will be rewarded."],
  ["Person ready to give up", "Every step forward is progress."],
  ["Person ready to give up", "Remember why you started."],
  ["Person ready to give up", "You are stronger than you think."],
  ["Person ready to give up", "Don’t let temporary setbacks stop you."],
  ["Person ready to give up", "Keep pushing; you are closer than you realize."],
  ["Person ready to give up", "Your persistence will pay off."],
  ["Person ready to give up", "The only way to fail is to quit."],
  ["Person ready to give up", "Believe in your journey."],
  ["Person ready to give up", "You have the power to overcome this."],
  ["Person ready to give up", "Your hard work will lead to success."],
  ["Person ready to give up", "Every challenge is an opportunity."],
  ["Person ready to give up", "Keep your eyes on the prize."],
  ["Person ready to give up", "You are capable of achieving your goals."],
  ["Person on the come up", "You will lose people you thought were permanent"],
  ["Person on the come up", "It will be tough but you’re very capable."],
  ["Person on the come up", "Stay focused on your goals."],
  ["Person on the come up", "Success requires perseverance and dedication."],
  ["Person on the come up", "Keep pushing forward; you are making progress."],
  [
    "Person on the come up",
    "Embrace the challenges; they are part of the journey.",
  ],
  ["Person on the come up", "Your hard work will pay off."],
  ["Person on the come up", "Trust the process; success takes time."],
  ["Person on the come up", "Stay committed to your vision."],
  [
    "Person on the come up",
    "You are building a strong foundation for your future.",
  ],
  [
    "Person on the come up",
    "Every step forward is a step closer to your dreams.",
  ],
  ["Person on the come up", "Believe in your abilities."],
  ["Person on the come up", "Surround yourself with positivity and support."],
  ["Person on the come up", "Your potential is limitless."],
  ["Person on the come up", "Keep striving for excellence."],
  ["Person on the come up", "Success is a journey"],
  [
    "Person on the come up",
    "Your efforts are creating a better future for yourself.",
  ],
  ["Person on the come up", "Stay resilient and determined."],
  ["Person on the come up", "You are capable of achieving greatness."],
  ["Person on the come up", "The journey may be tough"],
  ["Person with low motivation", "When you don’t have motivation"],
  ["Person with low motivation", "Take small steps to build momentum."],
  ["Person with low motivation", "Remember your ‘why.’"],
  ["Person with low motivation", "Focus on the progress you’ve made so far."],
  ["Person with low motivation", "Break your tasks into smaller"],
  ["Person with low motivation", "Reward yourself for completing tasks."],
  ["Person with low motivation", "Find an accountability partner."],
  [
    "Person with low motivation",
    "Change your environment to boost productivity.",
  ],
  ["Person with low motivation", "Take breaks to recharge."],
  ["Person with low motivation", "Stay positive and focus on your goals."],
  ["Person with low motivation", "Revisit your goals and adjust if necessary."],
  ["Person with low motivation", "Surround yourself with inspiration."],
  ["Person with low motivation", "Visualize your success."],
  [
    "Person with low motivation",
    "Stay consistent; habits are built over time.",
  ],
  ["Person with low motivation", "Find motivation in small victories."],
  ["Person with low motivation", "Keep a journal of your progress."],
  ["Person with low motivation", "Stay committed to your journey."],
  [
    "Person with low motivation",
    "Use positive affirmations to boost your mindset.",
  ],
  ["", ""],
  ["", ""],
  ["Person with low motivation", "Focus on the benefits of completing tasks."],
  ["Person with low motivation", "Keep your end goal in sight."],
  ["Person with low self-esteem", "You are worthy just as you are."],
  ["Person with low self-esteem", "Believe in your inherent value."],
  ["Person with low self-esteem", "You have unique strengths and talents."],
  ["Person with low self-esteem", "Your worth is not defined by others."],
  [
    "Person with low self-esteem",
    "Be kind to yourself; self-love is essential.",
  ],
  ["Person with low self-esteem", "You deserve happiness and success."],
  ["Person with low self-esteem", "Trust in your abilities."],
  ["Person with low self-esteem", "You are enough"],
  ["Person with low self-esteem", "Celebrate your achievements"],
  [
    "Person with low self-esteem",
    "Embrace your imperfections; they make you unique.",
  ],
  [
    "Person with low self-esteem",
    "Surround yourself with positive influences.",
  ],
  ["Person with low self-esteem", "Take time to appreciate yourself."],
  ["Person with low self-esteem", "You are capable of amazing things."],
  ["Person with low self-esteem", "Believe in your potential."],
  ["Person with low self-esteem", "Focus on your strengths."],
  ["Person with low self-esteem", "You are valuable and irreplaceable."],
  ["Person with low self-esteem", "Your self-worth comes from within."],
  ["Person with low self-esteem", "Embrace your individuality."],
  [
    "Person with low self-esteem",
    "You have a unique contribution to make to the world.",
  ],
  ["Person with low self-esteem", "You are loved and appreciated."],
  ["Person with trust issues", "Trust is built over time"],
  ["Person with trust issues", "It’s okay to be cautious"],
  ["Person with trust issues", "Trust starts with being honest with yourself."],
  ["Person with trust issues", "Healing past wounds is key to building trust."],
  ["Person with trust issues", "Open your heart slowly; it’s a process."],
  [
    "Person with trust issues",
    "Trusting yourself is the first step to trusting others.",
  ],
  ["Person with trust issues", "Give people the chance to earn your trust."],
  ["Person with trust issues", "Communication is essential in building trust."],
  ["Person with trust issues", "Be patient with yourself and others."],
  [
    "Person with trust issues",
    "It’s okay to set boundaries while building trust.",
  ],
  [
    "Person with trust issues",
    "Trust is a gift that should be given carefully.",
  ],
  [
    "Person with trust issues",
    "Take time to understand and address your fears.",
  ],
  ["Person with trust issues", "Trust is a mutual journey"],
  ["Person with trust issues", "Be transparent about your concerns."],
  ["Person with trust issues", "Building trust is a sign of strength"],
  [
    "Person with trust issues",
    "It’s okay to seek support when rebuilding trust.",
  ],
  ["Person with trust issues", "Trust yourself to make the right decisions."],
  [
    "Person with trust issues",
    "Each step towards trust is a step towards healing.",
  ],
  ["Person with trust issues", "Trust is fragile but can be rebuilt."],
  [
    "Person with trust issues",
    "Trusting again is a sign of courage and growth.",
  ],
  ["Person people walk over", "Stand firm in your boundaries."],
  ["Person people walk over", "Your kindness is a strength"],
  ["Person people walk over", "Assertiveness is key to protecting your peace."],
  ["Person people walk over", "Your needs and feelings are important."],
  ["Person people walk over", "It’s okay to say no."],
  ["Person people walk over", "You deserve respect and consideration."],
  [
    "Person people walk over",
    "Establishing boundaries is a form of self-care.",
  ],
  [
    "Person people walk over",
    "Value yourself enough to stand up for yourself.",
  ],
  ["Person people walk over", "It’s okay to prioritize your well-being."],
  ["Person people walk over", "Speak up for what you believe in."],
  [
    "Person people walk over",
    "Respect yourself enough to walk away from disrespect.",
  ],
  ["Person people walk over", "Your voice matters."],
  ["Person people walk over", "Take ownership of your space and energy."],
  ["Person people walk over", "Set limits to protect your mental health."],
  ["Person people walk over", "It’s okay to be firm and kind simultaneously."],
  [
    "Person people walk over",
    "You have the right to protect your time and energy.",
  ],
  ["Person people walk over", "Don’t let others dictate your worth."],
  [
    "Person people walk over",
    "Your strength lies in your ability to stand up for yourself.",
  ],
  ["Person people walk over", "Boundaries are a form of self-respect."],
  [
    "Person people walk over",
    "It’s okay to distance yourself from toxic people.",
  ],
  ["Person with no confidence", "Confidence comes with action"],
  ["Person with no confidence", "Believe in your ability to grow and improve."],
  ["Person with no confidence", "Confidence is built through practice."],
  ["Person with no confidence", "Trust in your journey and your abilities."],
  [
    "Person with no confidence",
    "Embrace your strengths and work on your weaknesses.",
  ],
  ["Person with no confidence", "Every small victory boosts your confidence."],
  ["Person with no confidence", "Surround yourself with supportive people."],
  ["Person with no confidence", "Confidence is a muscle; the more you use it"],
  ["Person with no confidence", "Celebrate your achievements"],
  ["Person with no confidence", "Focus on your progress"],
  [
    "Person with no confidence",
    "You have the potential to achieve great things.",
  ],
  [
    "Person with no confidence",
    "Take risks; they are opportunities for growth.",
  ],
  ["Person with no confidence", "Believe in your unique talents and skills."],
  [
    "Person with no confidence",
    "Practice self-affirmation and positive thinking.",
  ],
  ["Person with no confidence", "Confidence is about progress"],
  ["Person with no confidence", "You are capable of more than you imagine."],
  ["Person with no confidence", "Trust yourself; you’ve got this."],
  ["Person with no confidence", "Confidence comes from within"],
  ["Person with no confidence", "Keep challenging yourself to grow."],
  ["Person with no confidence", "Believe in your journey and your potential."],
  ["Person ready for a change", "Embrace change"],
  [
    "Person ready for a change",
    "Change is uncomfortable but necessary for growth.",
  ],
  ["Person ready for a change", "Every change brings new opportunities."],
  [
    "Person ready for a change",
    "Change is the only constant in life; embrace it.",
  ],
  ["Person ready for a change", "Trust that change will lead to growth."],
  ["Person ready for a change", "Let go of the old to make room for the new."],
  ["Person ready for a change", "Change is the beginning of new adventures."],
  [
    "Person ready for a change",
    "Embrace the unknown; it’s where growth happens.",
  ],
  [
    "Person ready for a change",
    "Change brings new perspectives and opportunities.",
  ],
  ["Person ready for a change", "Don’t fear change; it’s a sign of progress."],
  ["Person ready for a change", "Change is a chance to reinvent yourself."],
  [
    "Person ready for a change",
    "Every change is a step towards self-improvement.",
  ],
  ["Person ready for a change", "Trust in the process of transformation."],
  ["Person ready for a change", "Change your mindset"],
  [
    "Person ready for a change",
    "Embrace change with open arms and an open mind.",
  ],
  ["Person ready for a change", "Change brings growth"],
  [
    "Person ready for a change",
    "Welcome change as an opportunity to learn and grow.",
  ],
  ["Person ready for a change", "Change is a natural part of life’s journey."],
  ["Person ready for a change", "Embrace change"],
  [
    "Person ready for a change",
    "Let change inspire you to become the best version of yourself.",
  ],
  ["Person with no hope", "Even in the darkest times"],
  [
    "Person with no hope",
    "Trust that this difficult moment is just one chapter in your journey",
  ],
  ["Person with no hope", "When you feel like giving up"],
  ["Person with no hope", "Hold on; your story is not over yet."],
  [
    "Person with no hope",
    "Hope is the whisper that keeps you going when the world is loud with doubt.",
  ],
  ["Person with no hope", "Small steps forward"],
  [
    "Person with no hope",
    "Hope can be found in the most unexpected places; keep looking.",
  ],
  ["Person with no hope", "Sometimes"],
  ["Person with no hope", "The sun will rise"],
  ["Person with no hope", "Hope is not lost"],
  [
    "Person with no hope",
    "Hold onto hope it will guide you through the darkness.",
  ],
  ["", ""],
  ["", ""],
  [
    "Person with no hope",
    "Even a small glimmer of hope can light up the darkest times.",
  ],
  ["Person with no hope", "You are stronger than you think"],
  ["Person with no hope", "When everything feels like an uphill battle"],
  ["Person with no hope", "Hope is a powerful force; let it guide you."],
  ["Person with no hope", "Every storm runs out of rain eventually."],
  ["Person with no hope", "Keep hope alive in your heart"],
  [
    "Person with no hope",
    "You are capable of finding light in the darkest places.",
  ],
  ["Person with no hope", "Let hope be the anchor in the storms of life."],
  ["Person with no hope", "Believe in the possibility of better days."],
  ["Person with no hope", "Even the darkest night will end"],
  ["Person with no discipline", "Start with small"],
  [
    "Person with no discipline",
    "Discipline is the bridge between goals and accomplishment.",
  ],
  ["Person with no discipline", "Consistency is key to building discipline."],
  ["Person with no discipline", "Create a routine and stick to it."],
  ["Person with no discipline", "Set clear goals and work towards them daily."],
  ["Person with no discipline", "Discipline is doing what needs to be done"],
  ["Person with no discipline", "Build habits that support your goals."],
  ["Person with no discipline", "Break tasks into manageable steps."],
  ["Person with no discipline", "Stay focused on your long-term goals."],
  ["Person with no discipline", "Celebrate small wins along the way."],
  ["Person with no discipline", "Find motivation in your progress."],
  ["Person with no discipline", "Surround yourself with disciplined people."],
  [
    "Person with no discipline",
    "Create an environment that fosters discipline.",
  ],
  [
    "Person with no discipline",
    "Use positive reinforcement to stay motivated.",
  ],
  ["Person with no discipline", "Visualize your success and stay committed."],
  ["Person with no discipline", "Track your progress and adjust as needed."],
  [
    "Person with no discipline",
    "Discipline requires perseverance and commitment.",
  ],
  ["Person with no discipline", "Stay accountable to yourself and others."],
  [
    "Person with no discipline",
    "Discipline is the foundation of a successful life.",
  ],
  ["Person with no discipline", "Keep pushing forward"],
  ["Person with a dream", "Chase your dream consistently."],
  ["Person with a dream", "Dreams are the blueprint to your future."],
  ["Person with a dream", "Never stop dreaming"],
  [
    "Person with a dream",
    "Turn your dreams into reality with persistent effort.",
  ],
  ["Person with a dream", "Dreams require action; take the first step."],
  ["Person with a dream", "Your dreams are valid and achievable."],
  ["Person with a dream", "Don’t let fear hold you back from your dreams."],
  ["Person with a dream", "Every dream begins with a single step."],
  ["Person with a dream", "Believe in the power of your dreams."],
  ["Person with a dream", "Your dreams are a reflection of your potential."],
  ["Person with a dream", "Keep your dreams alive"],
  ["Person with a dream", "Dreams are the roadmap to your future success."],
  ["Person with a dream", "Trust in your dreams"],
  ["Person with a dream", "Your dreams are the foundation of your journey."],
  ["Person with a dream", "Pursue your dreams with passion and determination."],
  [
    "Person with a dream",
    "Every dream is a possibility waiting to be realized.",
  ],
  [
    "Person with a dream",
    "Your dreams are the fuel that ignites your potential.",
  ],
  ["Person with a dream", "Don’t be afraid to dream big and aim high."],
  [
    "Person with a dream",
    "Dreams are the wings that will carry you to new heights.",
  ],
  ["Person with a dream", "Stay true to your dreams"],
  ["Person with a dream", "Embrace your dreams"],
  ["Person feeling overwhelmed", "Take one step at a time"],
  ["Person feeling overwhelmed", "It’s okay to pause and breathe."],
  ["Person feeling overwhelmed", "Break your tasks into smaller"],
  [
    "Person feeling overwhelmed",
    "Prioritize what’s most important and focus on that.",
  ],
  [
    "Person feeling overwhelmed",
    "Remember to take care of yourself amidst the chaos.",
  ],
  [
    "Person feeling overwhelmed",
    "You don’t have to do it all at once; take it one step at a time.",
  ],
  ["Person feeling overwhelmed", "It’s okay to ask for help when you need it."],
  [
    "Person feeling overwhelmed",
    "Focus on what you can control and let go of the rest.",
  ],
  ["Person feeling overwhelmed", "Take breaks to recharge your mind and body."],
  ["Person feeling overwhelmed", "Stay organized and keep a clear plan."],
  [
    "Person feeling overwhelmed",
    "It’s okay to delegate tasks to lighten your load.",
  ],
  ["Person feeling overwhelmed", "Keep a positive mindset and stay motivated."],
  [
    "Person feeling overwhelmed",
    "Don’t be afraid to say no to additional commitments.",
  ],
  ["Person feeling overwhelmed", "Focus on progress"],
  [
    "Person feeling overwhelmed",
    "Stay grounded and take things one day at a time.",
  ],
  ["Person feeling overwhelmed", "Find time for relaxation and self-care."],
  [
    "Person feeling overwhelmed",
    "Trust that you have the strength to get through this.",
  ],
  ["Person feeling overwhelmed", "Keep moving forward"],
  ["Person feeling overwhelmed", "Remember"],
  [
    "Person feeling overwhelmed",
    "You are capable of handling this; stay focused and determined.",
  ],
  ["Person in need of comfort", "It’s okay to feel down"],
  ["Person in need of comfort", "Allow yourself to rest and heal."],
  ["Person in need of comfort", "Take time to nurture your soul."],
  ["Person in need of comfort", "Surround yourself with love and support."],
  [
    "Person in need of comfort",
    "It’s okay to not be okay; give yourself permission to feel.",
  ],
  [
    "Person in need of comfort",
    "Comfort can be found in small moments of peace.",
  ],
  ["Person in need of comfort", "Lean on loved ones for support and comfort."],
  [
    "Person in need of comfort",
    "Remember that you are not alone in your struggles.",
  ],
  ["Person in need of comfort", "Take one day at a time"],
  [
    "Person in need of comfort",
    "Find solace in the things that bring you joy.",
  ],
  [
    "Person in need of comfort",
    "Be gentle with yourself during difficult times.",
  ],
  ["Person in need of comfort", "Healing is a process that takes time."],
  [
    "Person in need of comfort",
    "Allow yourself to grieve and process your emotions.",
  ],
  [
    "Person in need of comfort",
    "It’s okay to seek comfort in familiar routines.",
  ],
  ["Person in need of comfort", "Let go of expectations and just be."],
  ["Person in need of comfort", "Find peace in the present moment."],
  [
    "Person in need of comfort",
    "Take time to care for your mental and emotional well-being.",
  ],
  ["Person in need of comfort", "You are stronger than you think"],
  [
    "Person in need of comfort",
    "Comfort yourself with positive thoughts and affirmations.",
  ],
  ["Person in need of comfort", "Trust that this too shall pass"],
  ["Person feeling lonely", "You are not alone"],
  ["Person feeling lonely", "Reach out"],
  ["Person feeling lonely", "Loneliness is a feeling"],
  ["Person feeling lonely", "Take steps to connect with others."],
  ["Person feeling lonely", "You are worthy of love and connection."],
  ["Person feeling lonely", "Find comfort in your own company."],
  ["Person feeling lonely", "Reach out to friends and family for support."],
  ["Person feeling lonely", "Engage in activities that bring you joy."],
  ["Person feeling lonely", "Remember that loneliness is temporary."],
  ["Person feeling lonely", "Build new connections and friendships."],
  ["Person feeling lonely", "You are stronger than you realize."],
  ["Person feeling lonely", "Embrace self-love and self-compassion."],
  ["Person feeling lonely", "You have the power to change your situation."],
  ["Person feeling lonely", "Connect with others who share your interests."],
  ["Person feeling lonely", "Take care of your mental and emotional health."],
  ["Person feeling lonely", "Find solace in nature and quiet moments."],
  ["Person feeling lonely", "Seek out community and social support."],
  ["Person feeling lonely", "Focus on building meaningful connections."],
  ["Person feeling lonely", "Remember"],
  [
    "Person feeling lonely",
    "Find peace in solitude and use it for self-reflection.",
  ],
  ["Person feeling stuck", "Sometimes you have to step back to move forward"],
  ["", ""],
  ["", ""],
  [
    "Person feeling stuck",
    "Your current situation is not your final destination.",
  ],
  ["Person feeling stuck", "Embrace the opportunity for growth."],
  ["Person feeling stuck", "Take small steps to create momentum."],
  ["Person feeling stuck", "Reflect on what’s holding you back."],
  ["Person feeling stuck", "Every step forward is progress"],
  ["Person feeling stuck", "Change your perspective"],
  ["Person feeling stuck", "Trust that you will find a way forward."],
  ["Person feeling stuck", "Seek guidance and advice from others."],
  ["Person feeling stuck", "Focus on what you can control."],
  [
    "Person feeling stuck",
    "Stay positive and believe in your ability to overcome this.",
  ],
  [
    "Person feeling stuck",
    "Reevaluate your goals and make adjustments if needed.",
  ],
  ["Person feeling stuck", "Sometimes the first step is the hardest"],
  ["Person feeling stuck", "Your potential is limitless"],
  ["Person feeling stuck", "Embrace change as a way to move forward."],
  ["Person feeling stuck", "Every challenge is an opportunity for growth."],
  ["Person feeling stuck", "Stay resilient and keep moving forward."],
  ["Person feeling stuck", "Take time to recharge and refocus."],
  ["Person feeling stuck", "Trust that you will find your way."],
  ["Person feeling stuck", "You have the power to change your situation."],
  [
    "Person in self-doubt",
    "Doubt is a sign you’re growing beyond your comfort zone.",
  ],
  ["Person in self-doubt", "Trust your journey"],
  [
    "Person in self-doubt",
    "Self-doubt is normal; it means you’re pushing your limits.",
  ],
  ["Person in self-doubt", "Believe in your abilities and strengths."],
  [
    "Person in self-doubt",
    "Trust that you are capable of achieving great things.",
  ],
  ["Person in self-doubt", "Self-doubt is a part of growth; embrace it."],
  ["Person in self-doubt", "You are stronger than your doubts."],
  ["Person in self-doubt", "Focus on your progress"],
  ["Person in self-doubt", "Every step forward"],
  ["Person in self-doubt", "Surround yourself with positivity and support."],
  ["Person in self-doubt", "Trust that you are on the right path."],
  [
    "Person in self-doubt",
    "Self-doubt is a reminder that you’re challenging yourself.",
  ],
  [
    "Person in self-doubt",
    "Believe in your potential and keep moving forward.",
  ],
  [
    "Person in self-doubt",
    "Embrace self-doubt as a stepping stone to success.",
  ],
  ["Person in self-doubt", "You are capable of overcoming any obstacle."],
  [
    "Person in self-doubt",
    "Stay focused on your goals and keep pushing forward.",
  ],
  [
    "Person in self-doubt",
    "Every challenge you face is an opportunity for growth.",
  ],
  [
    "Person in self-doubt",
    "Trust in your abilities and keep striving for success.",
  ],
  [
    "Person in self-doubt",
    "Self-doubt is temporary; your strength is permanent.",
  ],
  ["Person in self-doubt", "Believe in yourself and your journey."],
  ["Person who failed", "Failure is not the end"],
  ["Person who failed", "Learn from failure"],
  ["Person who failed", "Every failure is an opportunity to grow and improve."],
  ["Person who failed", "Failure is a part of the journey to success."],
  ["Person who failed", "Embrace failure as a learning experience."],
  ["Person who failed", "Your failures do not define you; they refine you."],
  ["Person who failed", "Keep pushing forward; success is built on failures."],
  ["Person who failed", "Every setback is a setup for a comeback."],
  ["Person who failed", "Failure is just a stepping stone to greatness."],
  ["Person who failed", "Learn from your mistakes and keep moving forward."],
  ["Person who failed", "Failure is a part of life’s journey."],
  [
    "Person who failed",
    "Use failure as motivation to keep striving for success.",
  ],
  ["Person who failed", "Each failure brings you closer to your goals."],
  [
    "Person who failed",
    "Failure is temporary; your determination is permanent.",
  ],
  [
    "Person who failed",
    "Every great success is built on a foundation of failures.",
  ],
  ["Person who failed", "Your failures are just lessons in disguise."],
  ["Person who failed", "Keep learning"],
  [
    "Person who failed",
    "Failure is an opportunity to start again with more experience.",
  ],
  ["Person who failed", "Embrace failure as a part of your growth journey."],
  [
    "Person who failed",
    "Your resilience in the face of failure will lead to success.",
  ],
  ["Person seeking happiness", "Happiness is found within"],
  ["Person seeking happiness", "Cultivate joy in the little things."],
  ["Person seeking happiness", "True happiness comes from within."],
  [
    "Person seeking happiness",
    "Focus on the present moment and find joy in it.",
  ],
  ["Person seeking happiness", "Happiness is a choice you make every day."],
  [
    "Person seeking happiness",
    "Seek happiness in the simple pleasures of life.",
  ],
  ["Person seeking happiness", "Your happiness is your responsibility."],
  ["Person seeking happiness", "Find joy in the journey"],
  ["Person seeking happiness", "Happiness is a state of mind; cultivate it."],
  [
    "Person seeking happiness",
    "Create your own happiness through positive actions.",
  ],
  ["Person seeking happiness", "Happiness is a journey"],
  ["Person seeking happiness", "Embrace the present and find joy in it."],
  ["Person seeking happiness", "Focus on what makes you happy and pursue it."],
  ["Person seeking happiness", "Happiness is a habit; develop it."],
  ["Person seeking happiness", "True happiness is found in a life well-lived."],
  ["Person seeking happiness", "Seek happiness in meaningful connections."],
  ["Person seeking happiness", "Choose happiness over perfection."],
  ["Person seeking happiness", "Happiness is contagious; spread it."],
  [
    "Person seeking happiness",
    "Find happiness in the beauty of everyday moments.",
  ],
  [
    "Person seeking happiness",
    "You deserve to be happy; pursue it relentlessly.",
  ],
  ["Person dealing with grief", "Grief is a testament to the love you had."],
  ["Person dealing with grief", "Take your time"],
  ["Person dealing with grief", "Grief is a process"],
  [
    "Person dealing with grief",
    "Allow yourself to feel and express your emotions.",
  ],
  [
    "Person dealing with grief",
    "Healing takes time; be patient with yourself.",
  ],
  ["Person dealing with grief", "Your grief is a reflection of your love."],
  [
    "Person dealing with grief",
    "Take one day at a time; healing is a journey.",
  ],
  ["Person dealing with grief", "It’s okay to not be okay."],
  [
    "Person dealing with grief",
    "Allow yourself to grieve and heal in your own time.",
  ],
  ["Person dealing with grief", "Grief is a sign of the depth of your love."],
  [
    "Person dealing with grief",
    "Healing comes in waves; allow yourself to ride them.",
  ],
  [
    "Person dealing with grief",
    "Your loved one’s memory will always be with you.",
  ],
  [
    "Person dealing with grief",
    "It’s okay to seek support and comfort from others.",
  ],
  ["Person dealing with grief", "Grief is a natural response to loss."],
  ["Person dealing with grief", "Take time to honor your loved one’s memory."],
  [
    "Person dealing with grief",
    "Healing is a gradual process; be kind to yourself.",
  ],
  ["Person dealing with grief", "Allow yourself to remember the good times."],
  [
    "Person dealing with grief",
    "Your grief is a testament to the bond you shared.",
  ],
  [
    "Person dealing with grief",
    "It’s okay to feel sad; it’s a part of the healing process.",
  ],
  ["Person dealing with grief", "Trust that with time"],
  [
    "Person feeling unappreciated",
    "Your value is not diminished by others’ inability to see it.",
  ],
  ["Person feeling unappreciated", "Recognize your own worth"],
  ["Person feeling unappreciated", "You are valuable and worthy"],
  [
    "Person feeling unappreciated",
    "Your worth is inherent and not dependent on external validation.",
  ],
  [
    "Person feeling unappreciated",
    "Appreciate yourself and the unique qualities you bring.",
  ],
  ["Person feeling unappreciated", "Your contributions matter"],
  [
    "Person feeling unappreciated",
    "You are worthy of recognition and respect.",
  ],
  ["Person feeling unappreciated", "Believe in your own value and self-worth."],
  ["Person feeling unappreciated", "Your efforts are important"],
  [
    "Person feeling unappreciated",
    "Appreciate yourself and your achievements.",
  ],
  [
    "Person feeling unappreciated",
    "Your worth is not defined by others’ opinions.",
  ],
  ["Person feeling unappreciated", "You deserve to be valued and appreciated."],
  ["Person feeling unappreciated", ""],
  ["", ""],
  ["Take pride in your work and your efforts.", ""],
  ["Person feeling unappreciated", "Your self-worth comes from within"],
  [
    "Person feeling unappreciated",
    "You are deserving of love and appreciation.",
  ],
  [
    "Person feeling unappreciated",
    "Your value is not diminished by others’ inability to see it.",
  ],
  [
    "Person feeling unappreciated",
    "Recognize your own worth and celebrate it.",
  ],
  ["Person feeling unappreciated", "You are valuable"],
  [
    "Person feeling unappreciated",
    "Your worth is independent of external validation.",
  ],
  ["Person feeling unappreciated", "Believe in your own value and self-worth."],
  ["Person experiencing burnout", "Rest is essential"],
  ["Person experiencing burnout", "You are not a machine"],
  ["Person experiencing burnout", "Take time to rest and recharge."],
  ["Person experiencing burnout", "Your health and well-being come first."],
  ["Person experiencing burnout", "It’s okay to take a break and rest."],
  [
    "Person experiencing burnout",
    "Listen to your body and give it the rest it needs.",
  ],
  ["Person experiencing burnout", "Take care of yourself; you deserve it."],
  ["Person experiencing burnout", "Burnout is a sign that you need to rest."],
  [
    "Person experiencing burnout",
    "Prioritize your mental and emotional well-being.",
  ],
  ["Person experiencing burnout", "Rest is not a luxury; it’s a necessity."],
  ["Person experiencing burnout", "Take time for self-care and relaxation."],
  ["Person experiencing burnout", "It’s okay to slow down and take a break."],
  [
    "Person experiencing burnout",
    "Your well-being is more important than productivity.",
  ],
  ["Person experiencing burnout", "Take a step back and recharge."],
  [
    "Person experiencing burnout",
    "Listen to your body’s signals and rest when needed.",
  ],
  [
    "Person experiencing burnout",
    "Your health is your greatest asset; take care of it.",
  ],
  [
    "Person experiencing burnout",
    "It’s okay to prioritize your well-being over work.",
  ],
  [
    "Person experiencing burnout",
    "Rest and relaxation are essential for recovery.",
  ],
  ["Person experiencing burnout", "Take time to rest"],
  [
    "Person experiencing burnout",
    "Your well-being is a priority; make time for self-care.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is unfolding with every step you take.",
  ],
  ["Person searching for purpose", "Purpose is found in the journey"],
  ["Person searching for purpose", "Your purpose is a journey"],
  [
    "Person searching for purpose",
    "Trust that you will find your purpose in time.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is unique to you; embrace it.",
  ],
  [
    "Person searching for purpose",
    "Every step you take brings you closer to your purpose.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is a reflection of your passions and talents.",
  ],
  [
    "Person searching for purpose",
    "Keep exploring and you will find your purpose.",
  ],
  [
    "Person searching for purpose",
    "Your purpose will reveal itself as you grow.",
  ],
  [
    "Person searching for purpose",
    "Trust in the process of discovering your purpose.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is a journey of self-discovery.",
  ],
  [
    "Person searching for purpose",
    "Embrace the journey of finding your purpose.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is a reflection of who you are.",
  ],
  [
    "Person searching for purpose",
    "Stay open to new possibilities and opportunities.",
  ],
  ["Person searching for purpose", "Your purpose is to be true to yourself."],
  [
    "Person searching for purpose",
    "Trust that your purpose will become clear in time.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is a lifelong journey of growth.",
  ],
  [
    "Person searching for purpose",
    "Keep seeking and you will find your purpose.",
  ],
  [
    "Person searching for purpose",
    "Your purpose is to live a life true to yourself.",
  ],
  [
    "Person searching for purpose",
    "Trust that you are on the path to discovering your purpose.",
  ],
  ["Person looking for love", "Love starts with loving yourself."],
  [
    "Person looking for love",
    "The right love will find you when you’re ready.",
  ],
  ["Person looking for love", "True love begins with self-love."],
  [
    "Person looking for love",
    "Love will come when you are ready to receive it.",
  ],
  ["Person looking for love", "The love you seek is also seeking you."],
  [
    "Person looking for love",
    "Embrace self-love and the right love will follow.",
  ],
  ["Person looking for love", "Love yourself first"],
  ["Person looking for love", "You are deserving of love and happiness."],
  [
    "Person looking for love",
    "The right person will appreciate and love you for who you are.",
  ],
  ["Person looking for love", "Love will find you when you least expect it."],
  [
    "Person looking for love",
    "Focus on becoming the best version of yourself.",
  ],
  [
    "Person looking for love",
    "The love you give yourself sets the standard for others.",
  ],
  [
    "Person looking for love",
    "Be open to love and it will find its way to you.",
  ],
  ["Person looking for love", "Love is patient"],
  [
    "Person looking for love",
    "You are worthy of a love that is pure and true.",
  ],
  ["Person looking for love", "Love yourself first and foremost."],
  ["Person looking for love", "The right love will come at the right time."],
  [
    "Person looking for love",
    "Trust that you will find love when you are ready.",
  ],
  [
    "Person looking for love",
    "Focus on self-love and the right love will come.",
  ],
  ["Person looking for love", "The love you seek is already within you."],
  ["Person facing rejection", "Rejection is redirection"],
  [
    "Person facing rejection",
    "Every “no” brings you closer to the right “yes.”",
  ],
  ["Person facing rejection", "Rejection is not the end"],
  [
    "Person facing rejection",
    "Trust that rejection is leading you to something better.",
  ],
  ["Person facing rejection", "Rejection is a part of the journey to success."],
  [
    "Person facing rejection",
    "Every rejection is a step towards your true path.",
  ],
  [
    "Person facing rejection",
    "Rejection is an opportunity to grow and improve.",
  ],
  ["Person facing rejection", "Keep moving forward; rejection is not the end."],
  ["Person facing rejection", "Trust that something better is on the horizon."],
  [
    "Person facing rejection",
    "Rejection is a sign that you are pushing your limits.",
  ],
  [
    "Person facing rejection",
    "Learn from rejection and use it to fuel your determination.",
  ],
  ["Person facing rejection", "Rejection is a stepping stone to success."],
  [
    "Person facing rejection",
    "Every rejection is a redirection to something greater.",
  ],
  [
    "Person facing rejection",
    "Trust that rejection is a part of your journey.",
  ],
  ["Person facing rejection", "Rejection is a sign of your courage to try."],
  ["Person facing rejection", "Keep striving"],
  ["Person facing rejection", "Rejection is a chance to refine your path."],
  [
    "Person facing rejection",
    "Trust that you are being guided to something better.",
  ],
  ["Person facing rejection", "Rejection is a part of life’s journey."],
  [
    "Person facing rejection",
    "Every “no” is a step closer to the right “yes.”",
  ],
  ["Person who feels lost", "It’s okay to feel lost"],
  ["Person who feels lost", "Trust that the path will reveal itself in time."],
  ["Person who feels lost", "Feeling lost is a part of finding yourself."],
  ["Person who feels lost", "Trust in the process of self-discovery."],
  ["Person who feels lost", "Every journey begins with feeling lost."],
  ["Person who feels lost", "Clarity will come with time and patience."],
  ["Person who feels lost", "Trust that you will find your way."],
  ["Person who feels lost", "It’s okay to not have all the answers right now."],
  [
    "Person who feels lost",
    "Embrace the uncertainty; it’s a part of your journey.",
  ],
  [
    "Person who feels lost",
    "You are not alone in feeling lost; many have been there.",
  ],
  ["Person who feels lost", "Trust in your inner compass to guide you."],
  [
    "Person who feels lost",
    "Take it one step at a time; the path will become clear.",
  ],
  [
    "Person who feels lost",
    "Every step you take brings you closer to clarity.",
  ],
  ["Person who feels lost", "Trust that you are on the right path"],
  [
    "Person who feels lost",
    "Feeling lost is a sign that you are ready for change.",
  ],
  ["Person who feels lost", "Your journey is unique and valuable."],
  [
    "Person who feels lost",
    "Trust the process; you are exactly where you need to be.",
  ],
  ["Person who feels lost", "Embrace the unknown; it’s where growth happens."],
  [
    "Person who feels lost",
    "Clarity comes from taking action and moving forward.",
  ],
  ["Person who feels lost", "Trust that you will find your way in time."],
  ["Person with anxiety", "Breathe deeply"],
  ["Person with anxiety", "Anxiety is temporary"],
  ["Person with anxiety", "Breathe through the anxiety; it will pass."],
  ["", ""],
  ["", ""],
  ["Person with anxiety", "You are stronger than your anxious thoughts."],
  ["Person with anxiety", "Take one step at a time; you can handle this."],
  ["Person with anxiety", "Focus on the present moment to calm your mind."],
  ["Person with anxiety", "You have the power to overcome your anxiety."],
  ["Person with anxiety", "Practice self-care to manage your anxiety."],
  ["Person with anxiety", "Remember"],
  [
    "Person with anxiety",
    "Take deep breaths and ground yourself in the present.",
  ],
  [
    "Person with anxiety",
    "You are capable of handling whatever comes your way.",
  ],
  ["Person with anxiety", "Focus on positive thoughts to calm your anxiety."],
  ["Person with anxiety", "Take it one moment at a time; you’ve got this."],
  ["Person with anxiety", "You are in control of your thoughts and feelings."],
  ["Person with anxiety", "Practice mindfulness to ease your anxiety."],
  [
    "Person with anxiety",
    "Trust that you can handle this; you are stronger than you think.",
  ],
  ["Person with anxiety", "Anxiety is a part of life"],
  [
    "Person with anxiety",
    "Focus on what you can control and let go of the rest.",
  ],
  [
    "Person with anxiety",
    "Take time for self-care and relaxation to manage your anxiety.",
  ],
  ["Person with anxiety", "You have the strength to overcome your anxiety."],
  ["Person seeking growth", "Growth happens outside of your comfort zone."],
  ["Person seeking growth", "Every challenge is an opportunity to grow."],
  ["Person seeking growth", "Embrace challenges as opportunities for growth."],
  [
    "Person seeking growth",
    "Growth requires stepping out of your comfort zone.",
  ],
  [
    "Person seeking growth",
    "Trust the process of growth and self-improvement.",
  ],
  ["Person seeking growth", "Every experience is a chance to learn and grow."],
  ["Person seeking growth", "Growth comes from pushing your limits."],
  ["Person seeking growth", "Embrace discomfort as a sign of growth."],
  [
    "Person seeking growth",
    "Every setback is an opportunity to grow stronger.",
  ],
  [
    "Person seeking growth",
    "Trust that you are growing with each step you take.",
  ],
  ["Person seeking growth", "Growth is a journey"],
  ["Person seeking growth", "Embrace change as a catalyst for growth."],
  ["Person seeking growth", "Every challenge is a stepping stone to growth."],
  ["Person seeking growth", "Growth requires patience and perseverance."],
  [
    "Person seeking growth",
    "Embrace the journey of self-discovery and growth.",
  ],
  ["Person seeking growth", "Growth comes from learning and adapting."],
  ["Person seeking growth", "Every experience"],
  ["Person seeking growth", "Embrace growth as a lifelong journey."],
  ["Person seeking growth", "Trust in your ability to grow and improve."],
  ["Person seeking growth", "Growth is a sign of progress and resilience."],
  [
    "Person seeking growth",
    "Embrace the process of becoming the best version of yourself.",
  ],
  [
    "Person needing courage",
    "Courage is feeling the fear and doing it anyway.",
  ],
  ["Person needing courage", "You are braver than you believe."],
  ["Person needing courage", "Take a deep breath and take the leap."],
  ["Person needing courage", "Trust in your strength and bravery."],
  ["Person needing courage", "Courage is taking action despite your fears."],
  ["Person needing courage", "You have the courage to overcome any obstacle."],
  ["Person needing courage", "Embrace your fears and face them head-on."],
  [
    "Person needing courage",
    "Courage is the first step to achieving your dreams.",
  ],
  ["Person needing courage", "Believe in your inner strength and courage."],
  [
    "Person needing courage",
    "Every act of courage brings you closer to your goals.",
  ],
  ["Person needing courage", "Trust that you have the courage to succeed."],
  ["Person needing courage", "Courage is not the absence of fear"],
  ["Person needing courage", "You are capable of more than you know."],
  ["Person needing courage", "Take bold steps towards your dreams."],
  ["Person needing courage", "Your courage will inspire others."],
  [
    "Person needing courage",
    "Trust in your ability to face challenges with courage.",
  ],
  ["Person needing courage", "Embrace courage as a way of life."],
  ["Person needing courage", "Every courageous act makes you stronger."],
  ["Person needing courage", "Believe in your capacity for courage."],
  ["Person needing courage", "Take the first step; your courage will follow."],
  ["Person scared of being seen ", "It's okay to take up space "],
  ["Person scared of being seen ", "You have so much to offer "],
];

export default labelMessagePairs;
