const wfts_quotes = [
  "You are enough. Just as you are right now. Even with your mistakes and imperfections, even though you’re still working on yourself,  you are enough. Now go be unapologetically you and shine.",
  "Don't let your fears hold you back. You can only reach a new version of yourself by doing something new. This can be scary, but facing your fears will show you how strong and brave you truly are.",
  "You belong here. You are worthy of taking up space, being seen and being heard. Your presence is important and needed. Let them see you.",
  "Progress, not perfection. Don't you dare give up because you're not perfect at something. Any expert was once a beginner. Keep practicing, make progress. It'll get easier.",
  "You have the power. Change the parts of you that no longer serve you. Figure out what is standing in the way of your potential and work on it. It's up to you and only you to reach your goals. Get to work, you know you can do this.",
  "It’s okay to not be okay. We all have our moments. Every day is not going to be perfect. Take time to acknowledge your emotions. Figure out why you feel the way you feel. Take a break. Get some rest. But just don’t quit. Find the strength to keep going. You can and will get through this moment.",
  "Focus on you. Prioritize yourself today. Do something you love or something that makes you happy. You're allowed to put yourself first. Take care of you. ",
  "Surround yourself with people who value you and celebrate you as you become a better version of yourself. Let go of the ones who tear you down or mistreat you. Understand that you are worthy of respect and love and you should surround yourself only with people who treat you the way you need them to.",
  "It’s so easy to think about what could go wrong. But it’s so much more motivating to think about what could go right.",
  "Stop putting so much pressure on yourself. Yes, you have more learning to do. Yes, you have more work to do. But you also have time to do it. This isn’t a race. Be patient and give yourself grace along the way. You’ll get there eventually.",
  "Learn to love your own presence. Appreciate the ways that you are you. It’s okay to lean on others for comfort. But once you grow comfortable with yourself you'll start to find the peace that you deserve. Work on your relationship with yourself, it’s the most important one.",
  "You have to let go.  Something better than what you’re holding on to is on the way. Let go of the old and watch yourself grow as you do. It won't be easy but your future self will thank you. ",
  "Tough times are not meant to destroy you, they are meant to strengthen you. Find the lesson.",
  "Being perfect or having it all figured out is not the key to success. Instead it's persistence and discipline. You succeed when you decide to never give up. When you push through anyway. You have to fight for success and when you get there it’ll all be worth it.",
  "Never feel guilty for doing what is best for you. Keep showing up for yourself, again and again.",
  "Don’t miss out on something that could be life-changing just because it could also be difficult. You know you have what it takes.",
  "You show others how to treat you based on how you treat yourself. Be kind to yourself. Don't criticize everything you do. It’s important to evaluate and grow. But that doesn’t mean belittle yourself in the process. What you say to yourself truly matters. Be kind.",
  "Try not to overthink it.  Don’t let doubt creep in. Focus on the step in front of you not the whole staircase. Any progress is good progress. Be proud of how far you’ve come and keep moving forward, step by step.",
  "We all make mistakes. Forgive yourself for whatever mistakes you've made in the past. Right now, in this moment, you have the ability to change and become a better person, the person that you want to be. Your past version of you no longer has power. Forgive yourself. Grow. Make the change.",
  "Sometimes courage is simply saying to yourself at the end of a rough day “I’ll try again tomorrow”",
  "Stop holding yourself back. You are underestimating yourself and it isn’t fair to you. Don't settle for less. You are capable of so much more, you just have to actually try things that are new to you. Brave the unknown. You’ll be amazed at what you can do.",
  "Someone else’s opinion of you is not your reality. You are the author of your own life story. Write the pages as you desire. If you don't like this chapter, start a new one. You're in charge. Get creative.",
  "Love yourself enough to set boundaries. Prioritize yourself, your time and your energy. Those that truly love and respect you will understand.",
  "That dream you can’t stop thinking about is there for a reason. Don’t ignore it. Don’t run from it. Chase it. Go after it with everything you have. You’ll eventually understand why you can’t let it go. Be committed to following your dream, it’s calling you for a reason.",
  "It’s okay to feel lost or unsure sometimes. These moments are important parts of your journey. Try to figure out what these feelings are telling you and channel that energy into something you can use.",
  "Don’t get caught up in comparisons. This is your own path and you’ll get there on your own time. It’s not a race. Keep working. Have patience. And go at your own pace.",
  "Sometimes you have to be brave enough to take a chance on yourself. Take the leap. It will be challenging but nothing gets better if you stay in the same place. Go after it and don’t look back.",
  "Whenever you feel like giving up, remind yourself of why you started. While the journey may be tough, the destination will definitely be worth the struggle.",
  "Sometimes the most productive thing you can do is take a break and recharge. It’s not a waste of time, it’s an investment in your well-being.",
  "Don't let the worries of the future rob you of the joys of the present. One of the best ways to prepare for the future is to live in the present and make the most of every opportunity. The present moment is where life happens, don't miss it. ",
  "Manifesting is not just about asking the universe for what you want, it's also about aligning your actions and beliefs to make it happen. You have to do the work. You have to believe that you'll get there no matter how tough it is right now. It will be yours, keep going.",
  "Try to surround yourself with people who will hold your hand in the storm and also dance with you in the sunshine.",
  "Don't shrink yourself to fit in places you’ve outgrown. There is better out there for you. Go ahead and shine.",
  "Remember to take some time to appreciate the simple things. While the world can sometimes be a harsh place, there is still so much beauty that surrounds you. Cherish each moment that brings you peace and joy and be gentle with yourself along your journey.",
  "Trust in the timing of your life. Your path is uniquely yours and all things will fall into place when they are meant to. Just be patient.",
  "Sometimes your biggest obstacle is yourself. Don’t let doubt get in the way. Keep going and don’t stop until you’re proud.",
  "Stop carrying the weight of who you once were, let go and embrace the person you are meant to be.",
  "Make sure you input as much as you output. Pour into yourself just as much as you pour into your work and others. You are just as important.",
  "Just start right now. There will never be a perfect time, there will never be a perfect place. Get started just as you are. ",
  "Be open to accepting all forms of abundance that comes your way. You deserve every bit of greatness that you receive.",
  "Understand that you’re still making progress, even if the pace seems slow. It’s not a race, just focus on being better than you were yesterday. You’ll get there.",
  "A breakthrough is coming your way. Right now you may be struggling and unsure if you’ll make it to the other side. Don’t give up. Keep fighting. You are going to make it.",
  "Every time you stumble it’s simply a stepping stone; you’re only defeated if you decide to not take the next step. Stay committed and you’ll never truly fail.",
  "Don’t let a tough situation make you forget how far you’ve come. This difficult phase will not last forever. Have faith in yourself, you absolutely have what it takes to make it through.",
  "Be honest with yourself. Some of your habits are no longer serving you, even if they are comfortable. Release them and make the change. You will start to see yourself grow in ways you never imagined.",
  "That same kindness you give to others, you can also give to yourself. You deserve your own love and care just as much as anyone else.",
  "There’s a dream you have that you’re running away from. Maybe you’re scared or you don’t feel ready. No more running. Go after it with everything you have. You’ll see just how capable you truly are.",
  "Relax. Stop worrying so much about the future. Just focus on doing what you can right now and everything else will fall into place.",
  "Being positive doesn't mean you will be happy every single day. It means even on those rough days, you know that better days are ahead.",
  "Cherish those around you who bring you peace. The ones who celebrate your wins and motivate you to overcome your losses. The ones who lift you up, even when the world feels heavy. Treasure them, and be sure to show them your support as well.",
  "Be patient with yourself. You don’t have to figure everything out in one day. Your entire path doesn’t need to be planned all at once. Just take it step by step. And enjoy the journey.",
  "Your true growth will begin when you start to release the parts of you that you’ve outgrown",
  "Never give up on you. Even if you fall. Take a moment. Reset. Refocus. Learn from your mistakes and go at it again.",
  "Imagine what could happen if you stop doubting yourself. Get out of your own way and just get started. You have everything it takes. ",
  "You are allowed to prioritize yourself, even if that upsets other people. You’re not being selfish, your well-being matters too.",
  "Be proud of yourself. For all those silent battles you fought. For those moments when the path ahead seemed unclear but you kept going. You’re still here. You made it through. Be proud of your strength.",
  "It’s not too late. If you’re not where you want to be, you have the power to make a change. The best time for new beginnings is now.",
  "Believe in where you’re heading. Even if the path is unclear right now. It will end up working out, maybe even better than you could ever imagine.",
  "It’s unfair to yourself to expect perfection. Do what you can, with what you have, exactly where you are. That is enough.",
  "Trust that the changes happening in your life are for the better. It may seem scary right now, but eventually, you’ll see these changes were necessary.",
  "Always practice gratitude. Even as you strive for more, remember to cherish what you currently have. Gratitude opens the heart to more joy and abundance.",
  "Remind yourself that every moment of struggle is only temporary. The strength you gain from overcoming it will last a lifetime. Keep fighting, you're closer than you think.",
  "When fear whispers that you’re not good enough, let your dreams shout louder. Push past the doubt, and watch as you exceed your own expectations.",
  "Cherish those who truly see you - not just on your brigthest days but through all your seasons. The people who know your shadows and still see your light. Forever keep them close, they are precious. ",
  "Speak to yourself like you would to someone you love. Be kind, be understanding, be honest, and be supportive. Your words have power—use them to uplift and empower yourself.",
  "No two paths are the same. Be proud of your unique journey. You’re not late; you’re not early. You are exactly where you need to be.",
  "Remember to protect your energy. Not only is it okay for you to tell others no—it's sometimes necessary. Your energy is precious; treat it with care.",
  "Try not to dwell so much on the past or the future that you miss the beauty of now. This moment has something special for you, don’t miss it.",
  "Hard work pays off in ways that shortcuts never will. Don’t rush your dreams. Stay committed, stay focused, and give it your all. You'll be amazed at what you can achieve.",
  "When the road gets tough, take a moment to look back at how far you've already come. You've conquered mountains before, and you can do it again.",
  "Release the need for perfection and focus on being authentic, flaws and all. Your true self matters far more than trying to meet impossible standards. ",
  "Trust that by taking moments to slow down and be still, you are allowing yourself the space to heal, rest, and find inner peace. It's an important part of your journey.",
  "Falling off track isn't a reason to stop; it's an opportunity to show just how strong your comeback can be. Don't let this stumble define you; you are much stronger than you think.",
  "Don't let the past hold you back or the future overwhelm you. Be present in this moment, focus on your growth, and trust that everything will fall into place.",
  "Life may throw challenges your way, but remember, you have the strength to overcome any obstacle. You are a warrior, a survivor, a conqueror. Keep pushing forward.",
  "Empower yourself and break free from the limitations others may place on you. Define your own path and follow it with confidence.",
  "Just because self-doubt creeps in, doesn't mean you have to listen. Quiet the voice of uncertainty with affirmations of your worth and abilities. You are capable of achieving anything you set your mind to.",
  "In the pursuit of your dreams, don’t forget to pause and enjoy the journey. Balance is found in the moments of joy. Celebrate your small wins and savor the beauty in everyday experiences.",
  "Forgiveness is not about changing the past, but about changing your future. Choose to live a life free from the shadows of old wounds.",
  "True strength is not about force, but about resilience. It's about standing tall in the face of adversity and choosing to rise again, no matter how many times you fall.",
  "Never forget that the love and support from your loved ones are the greatest treasures you can have. Their presence in your life is a constant reminder that you are never alone. Hold on to them and cherish every moment.",
  "Growth is not always about achieving great things, but about the small, consistent steps you take every day to become a better version of yourself.",
  "Tough times don't last, but tough people do. Keep going, keep growing, and keep believing in the strength within you.",
  "Be your biggest supporter, let your own voice be the loudest cheer in your corner. Your self-confidence will open doors you never thought possible.",
  "Embrace the unknown with open arms, for it is in uncertainty that we discover our true potential. Let go of fear and trust the process.",
  "Gratitude turns what we have into enough. Focus on the blessings in your life, and you'll find that abundance surrounds you in ways you never imagined.",
  "A healthy relationship truly starts with loving yourself. When you honor your own worth, you attract people who respect and cherish you.",
  "Your value is inherent. You don’t need to prove your worth to anyone. Know your value, stand firm in it, and let it shine through everything you do.",
  "Things have a funny way of aligning for you when you least expect it. Trust the process and keep moving forward with faith and consistency.",
  "Your past does not define you. Yes, it has shaped you, but today you can start making changes for a future that aligns with your dreams and who you want to be.",
  "There will be days when your energy is low and you have no motivation to do anything. On those days, be kind to yourself and do what you can, even if it feels small.",
  "Sometimes the greatest strength lies in letting go. Release what no longer serves you and make room for new opportunities to flow into your life.",
  "Surround yourself with positivity. Energy is contagious. Choose to be in the company of those who uplift and inspire you, and strive to be that person for others.",
  "Every ending is a new beginning in disguise. Embrace the cycles of life, and trust that each chapter brings you closer to where you are meant to be.",
  "When you feel like giving up, remind yourself of all the times you pushed through and came out stronger on the other side. You are more resilient than you give yourself credit for.",
  "Setting boundaries is an act of self-love. It’s okay to say no. Protect your peace and nurture relationships that respect your limits.",
  "To those with no voice, your voice matters. Speak up for what you believe in and stand firm in your convictions. You have the power to make a difference.",
  "Don’t let the noise of others’ opinions drown out your own inner voice. Trust your instincts, stay true to your values, and make decisions that resonate with your true self.",
  "Be patient with yourself. Some days you can only give 10%, but those small efforts are building towards something greater.",
  "It's important to hold yourself accountable. You can't expect to see change if you don't make one. Recognize what's limiting you and take action to break free.",
  "In a relationship, it’s important to nurture each other’s individuality. Encourage each other’s passions and interests while building a life together.",
  "Nature has a way of teaching us patience. Just like the seasons, growth takes time. Trust that your efforts will bloom in their own season.",
  "Sometimes it feels like there's no way out and you’re stuck where you are forever. In those moments, remember, this too shall pass. Take a moment, breathe, and keep pushing through the storm. You will make it out.",
  "Allow yourself to let go of who you think you should be, and embrace who you truly are. The more you authentically show up in the world, the more you will attract the right opportunities and connections.",
  "Tough moments are a part of any relationship; nothing is perfect. In those times, you discover how truly committed you are to each other. Use these moments as opportunities to grow stronger and emerge better together.",
  "Every day is a new chance to start fresh. Let go of yesterday's burdens and embrace today with a hopeful heart and an open mind.",
  "Understand that fear is a liar that preys on your insecurities. You are stronger and braver than you realize. Challenge yourself to overcome your fear and tap into your true potential.",
  "Focus your energy on what you can control and release the need to control what you cannot. Peace comes from recognizing and accepting the difference between the two.",
  "True empowerment comes from understanding your worth. Know that you deserve to be treated with love and respect and you should never settle for anything less.",
  "Your dreams are worth fighting for. No matter how challenging the path may be, stay committed and keep your vision alive.",
  "You don't have to have it all figured out in a day. Take each step as it comes, savor the journey unfolding before you, and trust that you will eventually figure it out in time.",
  "It's important to know when to push forward and when to take a step back. Both are essential for progress. Listen to your inner voice and honor what your mind and body need.",
  "Sometimes things feel like they're falling apart when they're actually falling into place. Hang in there.",
  "The mind can be a restless sea, but you have the power to calm the waves. Quiet the noise, find stillness, and embrace the serenity within.",
  "It’s important to teach the people around you how to show up for you. Don’t be afraid to ask for what you desire. Your needs matter too.",
];

export default wfts_quotes;
